package com;
// Generated 26 Apr, 2020 1:29:07 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String id;
     private String password;

    public Admin() {
    }

    public Admin(String id, String password) {
       this.id = id;
       this.password = password;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


