package com;
// Generated 26 Apr, 2020 1:29:07 AM by Hibernate Tools 4.3.1



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private int id;
     private String b1;
     private String b2;
     private String b3;

    public Book() {
    }

    public Book(int id, String b1, String b2, String b3) {
       this.id = id;
       this.b1 = b1;
       this.b2 = b2;
       this.b3 = b3;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getB1() {
        return this.b1;
    }
    
    public void setB1(String b1) {
        this.b1 = b1;
    }
    public String getB2() {
        return this.b2;
    }
    
    public void setB2(String b2) {
        this.b2 = b2;
    }
    public String getB3() {
        return this.b3;
    }
    
    public void setB3(String b3) {
        this.b3 = b3;
    }




}


