package com;
// Generated 26 Apr, 2020 1:29:07 AM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private int id;
     private String cno;
     private String exp;
     private String cvv;
     private String coupon;

    public Payment() {
    }

    public Payment(int id, String cno, String exp, String cvv, String coupon) {
       this.id = id;
       this.cno = cno;
       this.exp = exp;
       this.cvv = cvv;
       this.coupon = coupon;
    }

    public Payment(Integer id, Integer card, Integer exp, Integer cvv, Integer coupon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    public String getExp() {
        return this.exp;
    }
    
    public void setExp(String exp) {
        this.exp = exp;
    }
    public String getCvv() {
        return this.cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }
    public String getCoupon() {
        return this.coupon;
    }
    
    public void setCoupon(String coupon) {
        this.coupon = coupon;
    }




}


