package com;
// Generated 26 Apr, 2020 1:29:07 AM by Hibernate Tools 4.3.1



/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String password;
     private String college;
     private String phno;

    public Register() {
    }

    public Register(String name, String email, String password, String college, String phno) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.college = college;
       this.phno = phno;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    public String getPhno() {
        return this.phno;
    }
    
    public void setPhno(String phno) {
        this.phno = phno;
    }




}


